spring:
  application:
    name: Online_Talim
  datasource:
    url: jdbc:postgresql://localhost:5432/Online_Talim
    username: postgres
    password: b1t
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  token:
    expiration:
      mills: 3600000000
    secret: U29tZVNlY3VyZVNlY3JldEtleUZvclRva2VuLWFzZGZhc2RmYXNkZmtqY2xpZmxqeHdkYmxzdWZqa3dlcmgyZmdyZWtmZ2ZyZQ==
